### ISSUE TITLE
Localization doesn't work (v0.14.3)

### ISSUE THREAD

**Issue by twens** [arfedulov/semantic-ui-calendar-react#117]
Localization doesn't work in v0.14.3 (by property and by direct use of moment)
In v0.14.2 it works

**Comment by xzessmedia** [comment]
I can confirm this

**Comment by arfedulov** [comment]
I'm going to fix it at the weekend.

``localization`` prop works, by the way.

**Comment by twens** [comment]
> `localization` prop works, by the way.
Unfortunately no.. At least for DateInput. But works in the previous version (0.14.2)

**Comment by arfedulov** [comment]
The bug was introduced here b70a11ece45b1d3a35c38394d458e99d39bdd07c. Even though we set locale on app level ``moment.locale('ru')``, moment is imported on module level and I guess this moment instance uses default locale. To avoid this, we need import locale on app level. Like this:

```jsx
import moment from 'moment';
import 'moment/locale/ru';
```
It sets locale globally. So fore example, you have global ``ru`` locale and if you need to change it programmatically you can use ``localization`` prop.

I update readme to explain this.

**Comment by arfedulov** [comment]
``localization`` prop works for me with v0.14.3. @twens could you test if the above explained solution works globally and with ``localization`` property?

**Comment by twens** [comment]
in v0.14.4  `localization `prop works correctly. 
what about global locale setting 
```
import moment from 'moment';
import 'moment/locale/ru';
```
it works only when I set any `localization  `prop. even empty string `localization=""`

**Comment by arfedulov** [comment]
It's something odd. It works for me perfectly.

**Comment by twens** [comment]
Strange. But anyway now it works and I close the issue
