### ISSUE TITLE
onBlur is not working for all input types

### ISSUE THREAD

**Issue by Kivylius** [arfedulov/semantic-ui-calendar-react#160]
**Describe the bug**
It is common to have onBlur (when in form, you focus away from the input) event to fire, usually the payload is same as the onChange, but for form validation, where focusing away from an input generates an error if the field is required.

**To Reproduce**
1. Go to any component'
2. Add onBlur prop
3. See error: Warning: Failed prop type: DateRangePicker: unknown props found: onBlur

**Expected behavior**
A onBlur event is fired.

* semantic-ui-react
* semantic-ui-css (or any alternative)
* semantic-ui-calendar-react

**Comment by arfedulov** [comment]
Is there ``onBlur`` *prop on semantic-ui-react*'s Input element? As far as I know there isn't, correct me if I'm wrong. 

This module is build on top of *semantic-ui-react* and deals with only date-picker related stuff. Handling input events is a low level task for this module and it relies on *semantic-ui-react* in things like that.

**Comment by wizapp** [comment]
Hi

I would like to use semantic-ui-calendar-react component in forms like [React Final Form](https://github.com/final-form/react-final-form), but I cannot since field validation never occurs.
Form Field validation occurs when onBlur event is fired.

It seems that [InputView::onBlur()](https://github.com/arfedulov/semantic-ui-calendar-react/blob/master/src/views/InputView.tsx) only calls its internal "closePopup()" function [here](https://github.com/arfedulov/semantic-ui-calendar-react/blob/6e3d80de743d7e7e87c9976fb8c0bdde4ed71f23/src/views/InputView.tsx#L174) but does not forward onBlur event.

**Comment by arfedulov** [comment]
solved in #171
