### ISSUE TITLE
Question : How can I reset the input box back to empty (and show the placeholder)

### ISSUE THREAD

**Issue by DanHibbert** [arfedulov/semantic-ui-calendar-react#35]
const datePickerProps = {
            onDateChange: date => this.handleDateChange(date),
            value : this.props.decisionDate || "",
            initialDate : this.props.decisionDate || "",
        };

return(
....
  <SemanticDatepicker clearable={true} {...datePickerProps} /> 
....);

I have a scenario where I set the date in the control and submit the data.  It then should reload the data (so this.props.decisionDate is null.  I expected that this would re-initialise the input field back the placeholder but it's still got the text in it.

Please could you advise on how to clear out the text field ?

Thanks
Dan

**Comment by arfedulov** [comment]
From this line ``<SemanticDatepicker clearable={true} {...datePickerProps} />``  it seems like you use some other calendar, not *semantic-ui-calendar-react*. Are you sure you use this package?

**Comment by Fluidbyte** [comment]
I'm having a similar issue (though I can confirm I'm using _semantic_ui-calendar_react_). After the user selects a date and time (and the value is stored in my model) they can come back and edit it, however, it starts in the last rendered "mode" (the minute selection).

Is there a way to set the mode back to the day so that they can basically start over. I'm aware they can click the header on the popup to go back, but it's not intuitive to users.

**Comment by arfedulov** [comment]
Yes, this behaviour is not convenient for users. But I'm not sure what is convenient.
I think that what definitely must be done is that when user clears the input field the input should
turn back to its initial state (currently it doesn't). Before this is implemented I would probably
enforce react to reinstantiate input component when its value is empty string by using ``key`` prop on that component.
I would update ``onChange`` handler like this:
```jsx
handleChange(e, { name, value }) {
    this.setState((prevState) => {
      let fieldKey = prevState[name + 'Key'];
      if (value === '') {
        fieldKey = fieldKey === 'a'? 'b': 'a';
      }
      return {
        [name]: value,
        [name + 'Key']: fieldKey,
      }
    });
  }
```
And set ``key`` prop on input component like this:
```jsx
<DateTimeInput
        placeholder="DateTime"
        key={this.state.dateTimeKey}
        name="dateTime"
        onChange={this.handleChange}
        value={this.state.dateTime} />
```
The other case I can imagine is when a user ends selecting a value (reaches the last `mode`) the input's mode turns back to its initial value. I don't know whether this is more user friendly? And I can't imagine right now how to make something like this from outside code.
I'll implement this in near future probably.

**Comment by Fluidbyte** [comment]
I've been hoping to have some time to fork and shoot you a PR (maybe this weekend), but my thought was to simply reset the mode/view via `onFocus`. Just going through QA with my team it seems like this is the most user friendly since the flow is shallow and feels like a single action (despite being 3 clicks).

Watching users QA this it seems like the desired behavior is to have the consistency of always going through the steps whether you're setting it from empty, or changing the date completely.

This could become a prop just with a boolean like `preserveLastMode` where:

```javascript
_onFocus () {
  if (!this.props.preserveLastMode) this.setState({ mode: this.props.startMode })
}
```

**Comment by arfedulov** [comment]
Yes, that would be great.

**Comment by Fluidbyte** [comment]
This is fairly hacky right now, just wanted to run it by you and get thoughts. It's pretty simple, but wasn't sure if you felt it applicable to other pickers.
