### ISSUE TITLE
Show selected day/month on Input picker popups

### ISSUE THREAD

**Issue by chen-ye** [arfedulov/semantic-ui-calendar-react#6]
Currently, the component will always open to the current month and day when popping up. If the input field has a value, instead it should open up to the value's month and day.

I can probably write a PR for this tomorrow.

**Comment by arfedulov** [comment]
@chen-ye I will appreciate it if you write a PR for this. :+1:

**Comment by arfedulov** [comment]
It partially solved since 313eb681c16cdd02d0d71c7fa49301ec8dabbe04. Currently date-picker showes date parsed from input field but it parses that value only on poping up. So if you change that value manually when date-pikcer is opened, picker does not reflect changes. I dont know if it's crutial but probably I will fix it in near future. 
Contributions are welcomed by the way.

**Comment by chen-ye** [comment]
Awesome! Should be good enough for me for now, but I might a PR at some point.

**Comment by arfedulov** [comment]
It solved now.
